import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';
import { ObjectType, Field, ID, InputType } from '@nestjs/graphql';

@ObjectType()
@InputType('WorkflowDefinitionInput')
@Entity()
export class WorkflowDefinition {
  @Field(() => ID)
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Field()
  @Column()
  name: string;

  @Field({ nullable: true })
  @Column({ nullable: true })
  displayName?: string;

  @Field({ nullable: true })
  @Column({ nullable: true })
  description?: string;

  @Field(() => String)
  @Column({ type: 'json' }) // Stores the workflow definition in JSON format
  definition: any;

  @Field(() => String)
  @Column({ type: 'json' }) // Stores the workflow graph structure
  graph: any;

  @Field(() => [String])
  @Column('text', { array: true })
  entities: string[]; // Entities this workflow operates on

  @Field(() => [String])
  @Column('text', { array: true })
  actions: string[]; // Actions this workflow uses

  @Field(() => Boolean)
  @Column({ default: true })
  isActive: boolean;

  @Field(() => Boolean)
  @Column({ default: false })
  isAutoGenerated: boolean; // Whether this was auto-generated from ontology

  @Field(() => String)
  @CreateDateColumn()
  createdAt: Date;

  @Field(() => String)
  @UpdateDateColumn()
  updatedAt: Date;
}