// Entity types
export interface Entity {
  id: string;
  name: string;
  displayName: string;
  description?: string;
  icon?: string;
  color?: string;
  properties: Property[];
  relations: Relation[];
  actions: Action[];
  rules: Rule[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Property {
  id: string;
  name: string;
  displayName: string;
  description?: string;
  type: 'STRING' | 'NUMBER' | 'BOOLEAN' | 'DATE' | 'DATETIME' | 'ENUM' | 'REFERENCE' | 'ARRAY' | 'OBJECT';
  required: boolean;
  unique: boolean;
  indexed: boolean;
  validationRules?: any;
  defaultValue?: any;
  enumValues?: string[];
  entityId: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Relation {
  id: string;
  name: string;
  displayName: string;
  description?: string;
  relationType: 'ONE_TO_ONE' | 'ONE_TO_MANY' | 'MANY_TO_ONE' | 'MANY_TO_MANY';
  fromCardinality: 'ONE' | 'ZERO_OR_ONE' | 'MANY' | 'ZERO_OR_MANY';
  toCardinality: 'ONE' | 'ZERO_OR_ONE' | 'MANY' | 'ZERO_OR_MANY';
  fromEntityId: string;
  toEntityId: string;
  properties?: any;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Action {
  id: string;
  name: string;
  displayName: string;
  description?: string;
  type: 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'CUSTOM' | 'WORKFLOW' | 'REPORT' | 'APPROVAL';
  entityId: string;
  parameters?: any;
  implementation?: any;
  script?: string;
  isActive: boolean;
  isSystemAction: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Rule {
  id: string;
  name: string;
  displayName: string;
  description?: string;
  type: 'VALIDATION' | 'COMPUTATION' | 'TRIGGER' | 'CONSTRAINT' | 'BUSINESS_LOGIC';
  scope: 'ENTITY' | 'PROPERTY' | 'RELATION' | 'GLOBAL';
  entityId: string;
  condition?: any;
  action?: any;
  expression?: string;
  isActive: boolean;
  isSystemRule: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// Workflow types
export interface WorkflowDefinition {
  id: string;
  name: string;
  displayName: string;
  description?: string;
  definition: any;
  graph: any;
  entities: string[];
  actions: string[];
  isActive: boolean;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface AgentSession {
  id: string;
  sessionId: string;
  userId: string;
  currentWorkflowId?: string;
  context: any;
  history: any[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface WorkflowExecution {
  id: string;
  workflowId: string;
  sessionId: string;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED';
  inputs: any;
  outputs: any;
  executionTrace: any;
  errorDetails?: any;
  createdAt: Date;
  updatedAt: Date;
}

// User and authentication types
export interface User {
  id: string;
  username: string;
  email: string;
  name: string;
  avatar?: string;
  department?: string;
  roles: string[];
  permissions: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Role {
  id: string;
  name: string;
  displayName: string;
  description?: string;
  permissions: string[];
  createdAt: Date;
  updatedAt: Date;
}

// Knowledge graph types
export interface KnowledgeGraph {
  entities: Entity[];
  graph: {
    from: any;
    relationship: any;
    to: any;
  }[];
}

// Chat UI types
export interface ChatMessage {
  id: string;
  content: string;
  sender: 'user' | 'agent';
  timestamp: Date;
  status?: 'sending' | 'delivered' | 'error';
  type?: 'text' | 'card' | 'table' | 'chart';
  data?: any;
}

export interface Conversation {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: Date;
}